site_name: nebula-docker
site_url: https://kozmoai.github.io/nebula-docker
repo_url: https://github.com/kozmoai/nebula-docker
edit_uri: edit/main/docs/
theme:
  name: material
  favicon: img/favicon.ico
  palette:
    primary: blue
    accent: blue
  icon:
    repo: fontawesome/brands/github
  logo:
    img/nebula-logo-mark.png
  font:
    text: Inter
    code: Source Code Pro
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
    - pymdownx.tabbed
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: True
            show_bases: True
            show_signature: False
            heading_level: 1
watch:
    - nebula_docker/
    - README.md
nav:
    - Home: index.md
    - Host: host.md
    - Credentials: credentials.md
    - Containers: containers.md
    - Images: images.md
    - Deployments:
      - Steps: deployments/steps.md
    - Worker: worker.md
extra:
    social:
        - icon: fontawesome/brands/slack
          link: https://www.nebula.io/slack/
        - icon: fontawesome/brands/discourse
          link: https://discourse.nebula.io/
        - icon: fontawesome/brands/youtube
          link: https://www.youtube.com/c/NebulaIO/videos
        - icon: fontawesome/regular/newspaper
          link: https://nebula.io/guide/
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/NebulaIO
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/company/nebula/
        - icon: fontawesome/brands/github
          link: https://github.com/kozmoai/nebula
        - icon: fontawesome/brands/docker
          link: https://hub.docker.com/r/kozmoai/nebula/
        - icon: fontawesome/brands/python
          link: https://pypi.org/project/nebula/
    analytics:
        provider: google
        property: G-8CSMBCQDKN
